# Using spring-ai-starter-mcp-server
spring:
  main:
    web-application-type: none
    banner-mode: off
  ai:
    mcp:
      server:
        name: stdio-mcp-server
        version: 1.0.0
        type: SYNC
logging:
  pattern:
    console:
